# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graypb = QtWidgets.QPushButton(self.centralwidget)
        self.graypb.setGeometry(QtCore.QRect(180, 450, 71, 41))
        self.graypb.setObjectName("graypb")
        self.invertpb = QtWidgets.QPushButton(self.centralwidget)
        self.invertpb.setGeometry(QtCore.QRect(280, 450, 71, 41))
        self.invertpb.setObjectName("invertpb")
        self.before = QtWidgets.QPushButton(self.centralwidget)
        self.before.setGeometry(QtCore.QRect(60, 200, 75, 23))
        self.before.setObjectName("before")
        self.after = QtWidgets.QPushButton(self.centralwidget)
        self.after.setGeometry(QtCore.QRect(650, 200, 75, 23))
        self.after.setObjectName("after")
        self.angleinput = QtWidgets.QTextEdit(self.centralwidget)
        self.angleinput.setGeometry(QtCore.QRect(370, 450, 71, 41))
        self.angleinput.setStyleSheet("font: 20pt \"Adobe Arabic\";")
        self.angleinput.setObjectName("angleinput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 431, 54, 21))
        self.label.setObjectName("label")
        self.rotatepb = QtWidgets.QPushButton(self.centralwidget)
        self.rotatepb.setGeometry(QtCore.QRect(450, 450, 61, 41))
        self.rotatepb.setObjectName("rotatepb")
        self.originpb = QtWidgets.QPushButton(self.centralwidget)
        self.originpb.setGeometry(QtCore.QRect(540, 450, 61, 41))
        self.originpb.setObjectName("originpb")
        self.piclabel = QtWidgets.QLabel(self.centralwidget)
        self.piclabel.setGeometry(QtCore.QRect(160, 50, 471, 321))
        self.piclabel.setStyleSheet("background-color: rgb(234, 255, 243)")
        self.piclabel.setText("")
        self.piclabel.setObjectName("piclabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Open_Pic = QtWidgets.QAction(MainWindow)
        self.Open_Pic.setObjectName("Open_Pic")
        self.Open_Filedir = QtWidgets.QAction(MainWindow)
        self.Open_Filedir.setObjectName("Open_Filedir")
        self.menu.addAction(self.Open_Pic)
        self.menu.addSeparator()
        self.menu.addAction(self.Open_Filedir)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.graypb.setText(_translate("MainWindow", "灰度化"))
        self.invertpb.setText(_translate("MainWindow", "反色"))
        self.before.setText(_translate("MainWindow", "上一张"))
        self.after.setText(_translate("MainWindow", "下一张"))
        self.angleinput.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Arabic\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))
        self.label.setText(_translate("MainWindow", "旋转角度"))
        self.rotatepb.setText(_translate("MainWindow", "旋转"))
        self.originpb.setText(_translate("MainWindow", "恢复原图"))
        self.menu.setTitle(_translate("MainWindow", "打开"))
        self.Open_Pic.setText(_translate("MainWindow", "图片文件"))
        self.Open_Filedir.setText(_translate("MainWindow", "图片文件夹"))
